---
title: "Almond Yield Function"
author: "Amanda Overbye & Matteo Torres"
date: "April 13, 2025"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(here)
library(tidyverse)
```

```{r}
clim <- read.table(here("data", "clim.txt"), header = TRUE)
```

```{r}
source(here("almond_yield_model.R"))
```

```{r}
#almond_yield_test(clim)
```

```{r}
function_test2 <- clim %>% 
group_by(year) %>%
        summarise(
            avg_feb_temp = mean(tmin_c[month == 2],na.rm = TRUE),
            total_jan_precip = sum(precip[month == 1],na.rm = TRUE)
        ) %>% 
        mutate(anomaly = -0.015 * avg_feb_temp - 0.0046 * avg_feb_temp^2 -
                0.07 * total_jan_precip + 0.0043 * total_jan_precip^2 + 0.28)
```

```{r}
anomaly_mean <- min(function_test$anomaly, na.rm = TRUE)
```


```{r}
anomaly_min <- min(function_test2$anomaly, na.rm = TRUE)
anomaly_max <- max(function_test2$anomaly, na.rm = TRUE)
anomaly_mean <- mean(function_test2$anomaly, na.rm = TRUE)

print(anomaly_max)
print(anomaly_min)
print(anomaly_mean)

```

